[package]
name = "polynomial-problem"
version = "0.1.0"
authors = ["Josh Rule <joshua.s.rule@gmail.com>", "Nicholas Alvarado <na2021@mit.edu>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/na2021/polynomial-problem"
homepage = "https://github.com/na2021/polynomial-problem"
description = "Rust simulations using input/output examples to learn typed first-order term rewriting systems that generalize the binomial expansion problem."
keywords = ["term-rewriting", "hindley-milner", "learning", "program-induction", "lists"]
categories = ["science", "simulation"]

[dependencies]
docopt = "1.0"
polytype = "6.0"
programinduction = "0.7"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
term_rewriting = "0.4"
toml = "0.4"

[patch.crates-io]
programinduction = { path = "../program-induction" }
term_rewriting = { path = "../term-rewriting-rs" }
polytype = { path = "../polytype-rs" }
